services:
  oshiire-core:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /mnt/host
        read_only: false
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"
